/ (root)
│
├── index.html              → Homepage (brief intro + project links)
├── automation-anywhere.html  → Page 1: Automation Anywhere Bot
├── selenium-testing.html     → Page 2: Selenium Automated Testing
├── manual-testing.html       → Page 3: Manual Testing
├── css/
│   └── style.css           → Stylesheet (shared across pages)
└── images/                 → Folder for project visuals (optional)